### ISSUE TITLE
warm_start not implemented yet?

### ISSUE THREAD

**Issue by ksehic** [QB3/sparse-ho#20]
Hi,

I was working with the weight LASSO model within sparse-ho with the plan to utilize the warm_start option. Similarly what we have in sklearn.linear_model.Lasso when you can pass predefined beta (i.e. w) coefficients with '.coef_' just before 'fit' function. However, as I can see in your code, this warm_start is not implemented. Maybe I'm missing something... If not, do you plan to implement that... Nevertheless, thank you for your help.

**Comment by QB3** [comment]
Hello,
Thx a lot for your question. Indeed there no .coef_ just before the fit: https://github.com/QB3/sparse-ho/blob/8da04002258acfc836d01839876bd3f5aa439bc8/sparse_ho/models.py#L227
But we have implemented it in a way to be to able to use a custom estimator: in particular one can use a customized sklearn estimator:
https://github.com/QB3/sparse-ho/blob/8da04002258acfc836d01839876bd3f5aa439bc8/examples/plot_held_out_lasso.py#L68 in particular one can use the option `warm_start=True` to benefit from warm start.
Does it answer you question?
