### ISSUE TITLE
SURE naming / API / generalization

### ISSUE THREAD

**Issue by svaiter** [QB3/sparse-ho#39]
Consider renaming `SURE` to something more in adequation with the
implementation. The current implementation follows [(Figure 3, Deledalle et al. 2020)](https://samuelvaiter.com/publications/deledalle2014sugar.pdf) by
implementing a smoothed version using Finite Difference Monte Carlo (FDMC)
method. A user testing the class might be confused to see that in low dimension,
a SURE implemented manually does not provide the same value as our `SURE` class.

I believe there is three possible options:
1. _Keep the current name._ This is probably the best way to not confuse people
   not familiar with the SURE. But in this case the documentation should reflect
   precisely why a user could observe a difference with a handcraft SURE.
2. _Change the name to one relevant to the litterature._ The more exact would be
   to use `FdmcSure` but this is a bit obscure for people and
   `FiniteDifferenceMonteCarloSure` maybe too explicit. Another option is to use
   SUGAR as it is easy to search. The issue is that SUGAR relates to the
   gradient of the criterion, which could be also confusing.
3. _Change the name to something clearer._ Maybe a `Smooth[ed]Sure` could be a
   candidate, but this is not a terminology which appears in papers.

### Parameters
- I don't understand why `SURE` takes `X_test` and `X_test` as parameters.
- Regarding `C` and `gamma_sure`. I believe it is not useful to expose them as
  parameters. Either the user does not want to play with it and two optional
  parameters are too much, or he really wants to control the finite difference
  step and it would be easier to directly access the member `epsilon`. The power
  law is advocated in the SUGAR paper, but different strategies could be used.

### Generalised SURE
It does not seem to be a priority, but this class could implements
generalization of the SURE to approximate the prediction risk and/or estimation
risk depending on the properties of `X`, which could be of interest for some use
(imaging for instance).

WDYT?

**Comment by QB3** [comment]
I would tend to vote for ```SmoothedSure``` with an quick explanation and a link toward the paper in the doc.

**Comment by QB3** [comment]
> I don't understand why SURE takes X_test and X_test as parameters

These parameters should be removed indeed

**Comment by QB3** [comment]
> Regarding C and gamma_sure. I believe it is not useful to expose them as
parameters. Either the user does not want to play with it and two optional
parameters are too much, or he really wants to control the finite difference
step and it would be easier to directly access the member epsilon. The power
law is advocated in the SUGAR paper, but different strategies could be used.

+1 I will remove them

**Comment by agramfort** [comment]
maybe MonteCarloSURE?

**Comment by svaiter** [comment]
> maybe MonteCarloSURE?
> 

The problem is that MC-sure is yet another estimator (figure 2 in the same paper) 😒

**Comment by agramfort** [comment]
FiniteDiffMonteCarloSure ?

>

**Comment by svaiter** [comment]
It sounds like a good ol' Java class! But I'm ok with it, it will be more precise than `SmoothedSure`.
