### ISSUE TITLE
CLN clean ho.py

### ISSUE THREAD

**Issue by QB3** [QB3/sparse-ho#43]
```ho.py``` is still a little bit dirty with old notation https://github.com/QB3/sparse-ho/blob/671947f27814351da0bc5ceeefe1f1bc73af4029/sparse_ho/ho.py#L89 from the code of Fabian.
@Klopfe is on it.

**Comment by Klopfe** [comment]
changed g_func to val_outer and grad_lambda to grad_outer to match the bilevel optimization structure.
