### ISSUE TITLE
FIX doc does not build when merging

### ISSUE THREAD

**Issue by QB3** [QB3/sparse-ho#44]
It seems that the doc does not not build automatically anymore https://github.com/QB3/sparse-ho/commit/671947f27814351da0bc5ceeefe1f1bc73af4029. I do not know why.

**Comment by agramfort** [comment]
see https://app.circleci.com/pipelines/github/QB3/sparse-ho

>

**Comment by mathurinm** [comment]
My guess is that it's because the commit message contains the list of all commits on the branch, and there's [ci skip] in some of them

@qb3 when you do the squash and merge you can clean the commit message

**Comment by mathurinm** [comment]
It looks OK for recent commits @QB3

**Comment by QB3** [comment]
Yes, it seems to work if there is no [ci skip] in the titles of commits.
We just need to make sure to change the name of the commit, without [ci skip].
