### ISSUE TITLE
ENH improve verbose output

### ISSUE THREAD

**Issue by mathurinm** [QB3/sparse-ho#60]
Using `verbose=True` in ImplicitForward yields "0 -st iterations over 100",  I am not sure what this is

In my expectations the basic print should be done by the optimizer, every time a new alpha is chosen, and the norm of the gradient for this corresponding alpha? Is this doable easily?

**Comment by QB3** [comment]
There are now 2 verbose paramters, one for the inner problem, and one for the outer, the value of the outer objective and the value of the norm of the gradient have been added here for the gradient descent: https://github.com/QB3/sparse-ho/blob/46184d9ce567fe7221963bacd4622d22ef7b2276/sparse_ho/optimizers/gradient_descent.py#L54

Is it good for you @mathurinm ?

**Comment by mathurinm** [comment]
Not so much, if i use `verbose=True` in ImplicitForward, i still see:
```0 -st iterations over 100
1 -st iterations over 100
2 -st iterations over 100
3 -st iterations over 100
4 -st iterations over 100
5 -st iterations over 100
6 -st iterations over 100
7 -st iterations over 100
8 -st iterations over 100
9 -st iterations over 100
10 -st iterations over 100
11 -st iterations over 100
0 -st iterations over 100
```
which does not help me a lot

**Comment by QB3** [comment]
Yes, you can do 
`ImplicitForward(verbose=False)`  and 
`GradientDescent(verbose=True)`

**Comment by mathurinm** [comment]
That's a different thing, I still think the output from ImplicitForward is not useful in its current form (+ it print 0st iteration.). can you not print some kind of value which is used a stopping criterion for the jacobian computation ?

Using `optimizer = LineSearch(n_outer=20, tol=1e-6, verbose=True)` yields:
```
value outer 1.4152773328855046
value outer 1.2832150163326204
value outer 1.26274067108345
value outer 1.2465399366900807
value outer 1.2628362380690947
value outer 1.2381518152201096
value outer 1.2269878566648114
value outer 1.2197605355875918
value outer 1.403941750639769
value outer 1.1956164121481545
value outer 1.1933375637012618
value outer 1.192762702904851
value outer 1.1907109072372584
```
can you display the number of iterations ? is 'outer' on par with the naming you have elsewhere ? Maybe tune the number of significant digits too ?
